version: "3.8"

services:
  superset:
    image: apache/superset
    container_name: "superset"
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: your_secret_key_here
    networks:
      default:
      doris_net:

networks:
  default:
  doris_net:
    ipam:
      config:
        - subnet: 172.20.80.0/24