version: "2.2"
services:
  jobmanager:
    image: flink:1.19.0
    container_name: "jobmanager"
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./conf/config.yaml:/opt/flink/conf/config.yaml
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        

  taskmanager:
    image: flink:1.19.0
    container_name: "taskmanager"
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    volumes:
      - ./conf/config.yaml:/opt/flink/conf/config.yaml
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2

  sql-client:
    image: flink:1.19.0
    container_name: "sqlclient"
    command: bin/sql-client.sh
    depends_on:
      - jobmanager
    volumes:
      - ./conf/config.yaml:/opt/flink/conf/config.yaml
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
