version: '3'

services:
  docker-fe:
    image: "apache/doris:1.2.2-fe-arm"
    container_name: "doris-fe"
    hostname: "fe"
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010
      - FE_ID=1
    ports:
      - "8030:8030"
      - "9030:9030"
    networks:
      doris_net:
        ipv4_address: 172.20.80.2
  docker-be:
    image: "apache/doris:1.2.2-be-arm"
    container_name: "doris-be"
    hostname: "be"
    depends_on:
      - docker-fe
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010
      - BE_ADDR=172.20.80.3:9050
    ports:
      - "8040:8040"
    networks:
      doris_net:
        ipv4_address: 172.20.80.3
  docker-broker:
    image: "apache/doris:1.2.2-broker-arm"
    container_name: "doris-broker"
    hostname: "broker"
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010
      - BROKER_ADDR=broker1:172.20.80.4:8000
    ports:
      - "8000:8000"
    networks:
      doris_net:
        ipv4_address: 172.20.80.4

networks:
  doris_net:
    ipam:
      config:
        - subnet: 172.20.80.0/16