version: "3.8"

services:
  alpine:
    image: fishep/alpine:latest
    container_name: alpine
    ports:
      - '1024:1024'
      - '1025:1025'
    command: [ "sh", "-c", "while true; do sleep 10; done;" ]