version: "3.8"

services:
  starrocks:
    image: starrocks/allin1-ubuntu
    container_name: "starrocks"
    ports:
      - "8030:8030"
      - "8040:8040"
      - "9030:9030"
    volumes:
      - paimon_data:/tmp/paimon

volumes:
  paimon_data: