spring:
  datasource:
    url: jdbc:mysql://mysql.dev:3306/demo
    username: demo
    password: demo
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:redis.dev}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl: ${REDIS_SSL:false}
      database: ${REDIS_DATABASE:0}
  elasticsearch:
    uris:
      - http://es.dev:9200
    username: elastic
    password: elastic

  kafka:
    bootstrap-servers: kafka.dev:9092
    consumer:
      group-id: kafka-consumer-group
