server:
  port: ${PORT:8080}
spring:
  application:
    name: spring-debug
  profiles:
    active: @profile@
#  main:
#    allowBeanDefinitionOverriding: true
liteflow:
  rule-source: config/flow_spring.el.xml