version: "3"

services:
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:v2.2.3
#    ports:
#      - "7848:7848"
#      - "8848:8848"
#      - "9848:9848"
#      - "9849:9849"
    env_file:
      - ./env/nacos-embedded.env

  nacos2:
    hostname: nacos2
    image: nacos/nacos-server:v2.2.3
    container_name: nacos2
#    ports:
#      - "17848:7848"
#      - "18848:8848"
#      - "19848:9848"
#      - "19849:9849"
    env_file:
      - ./env/nacos-embedded.env

  nacos3:
    hostname: nacos3
    image: nacos/nacos-server:v2.2.3
    container_name: nacos3
#    ports:
#      - "27848:7848"
#      - "28848:8848"
#      - "29848:9848"
#      - "29849:9849"
    env_file:
      - ./env/nacos-embedded.env