version: "3.8"

services:
  nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos
    env_file:
      - env/nacos-standlone.env
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8848/nacos" ]
      interval: 30s
      timeout: 3s
      retries: 3
