global:
  resolve_timeout: 5m
  smtp_from: 'fishep@qq.com'
  smtp_smarthost: 'smtp.qq.com:587'
  #smtp_smarthost: 'smtp.qq.com:465'
  smtp_auth_username: 'fishep@qq.com'
  smtp_auth_password: ''
  smtp_require_tls: true
  smtp_hello: 'qq.com'
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  #group_interval: 1m
  repeat_interval: 1h
  #repeat_interval: 1m
  receiver: 'web.hook'
  #receiver: 'email'
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'
  - name: 'email'
    email_configs:
      - to: 'fishep@qq.com'
        send_resolved: true
        #insecure_skip_verify: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
