version: "3.8"

services:
  elasticsearch:
    container_name: es
    image: elasticsearch:8.5.3
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    volumes:
      - ./plugins/ik:/usr/share/elasticsearch/plugins/ik
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3072M

volumes:
  es_data: