version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
#      - "443:443"
      - "8443:443"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
      - ./etc/nginx/ssl/:/etc/nginx/ssl/
#      - F:\project\fs\service:/var/www/service
#      - F:\project\fs\fs-manager:/var/www/fs-manager
#      - F:\project\fs\stats.fs.com:/var/www/stats.fs.com
      - ~/project/fs/service:/var/www/service
      - ~/project/fs/fs-manager:/var/www/fs-manager
      - ~/project/fs/stats.fs.com:/var/www/stats.fs.com