version: '3.6'
services:
  gitlab:
    image: 'registry.gitlab.cn/omnibus/gitlab-jh:latest'
    container_name: gitlab
#    restart: always
    hostname: 'gitlab.devops'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.devops'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
#    volumes:
#      - '$GITLAB_HOME/config:/etc/gitlab'
#      - '$GITLAB_HOME/logs:/var/log/gitlab'
#      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
