version: "2.2"
services:
  jobmanager:
    image: flink:1.19.0
    container_name: "jobmanager"
    ports:
      - "8081:8081"
#    command: standalone-job --job-classname com.job.ClassName [--job-id <job id>] [--jars /path/to/artifact1,/path/to/artifact2] [--fromSavepoint /path/to/savepoint] [--allowNonRestoredState] [job arguments]
    command: jobmanager
    volumes:
      - flink-home:/opt/flink
      - ./conf/config.yaml:/opt/flink/conf/config.yaml
      - paimon_data:/tmp/paimon
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2        

  taskmanager:
    image: flink:1.19.0
    container_name: "taskmanager"
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    volumes:
      - flink-home:/opt/flink
      - ./conf/config.yaml:/opt/flink/conf/config.yaml
      - paimon_data:/tmp/paimon
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 8
        parallelism.default: 2

volumes:
  flink-home:
  paimon_data: