CREATE DATABASE IF NOT EXISTS demo;
USE demo;
CREATE USER 'demo' IDENTIFIED BY 'demo';
GRANT ALL ON demo.* TO demo;
GRANT REPLICATION SLAVE ON *.* TO 'demo'@'%';
GRANT REPLICATION CLIENT ON *.* TO 'demo'@'%';
FLUSH PRIVILEGES;
