DROP TABLE IF EXISTS `T006A`;

CREATE TABLE `T006A` (
 `MANDT` VARCHAR(3) DEFAULT '000' NOT NULL ,
 `SPRAS` VARCHAR(1) DEFAULT '' NOT NULL ,
 `MSEHI` VARCHAR(3) DEFAULT '' NOT NULL ,
 `MSEH3` VARCHAR(3) DEFAULT '' NOT NULL ,
 `MSEH6` VARCHAR(6) DEFAULT '' NOT NULL ,
 `MSEHT` VARCHAR(10) DEFAULT '' NOT NULL ,
 `MSEHL` VARCHAR(30) DEFAULT '' NOT NULL ,
 PRIMARY KEY (`MANDT`, `SPRAS`, `MSEHI`)
);
 

 
-- CREATE FULLTEXT INDEX `esh:ftx~saphanadb~t006a~msehl~001` ON `SAPHANADB`.`T006A` (`MSEHL`) ASYNC PHRASE INDEX RATIO 0.200000 FUZZY SEARCH INDEX ON SEARCH ONLY OFF FAST PREPROCESS ON TEXT MINING OFF TEXT ANALYSIS OFF TOKEN SEPARATORS '\/;,.:-_()[]<>!?*@+{}=`&#$~|' COMPRESSION LEVEL 0;
-- CREATE FULLTEXT INDEX `esh:ftx~saphanadb~t006a~mseh3~001` ON `SAPHANADB`.`T006A` (`MSEH3`) ASYNC PHRASE INDEX RATIO 0.200000 FUZZY SEARCH INDEX ON SEARCH ONLY OFF FAST PREPROCESS ON TEXT MINING OFF TEXT ANALYSIS OFF TOKEN SEPARATORS '\/;,.:-_()[]<>!?*@+{}=`&#$~|' COMPRESSION LEVEL 0;
-- CREATE FULLTEXT INDEX `esh:ftx~saphanadb~t006a~mseht~001` ON `SAPHANADB`.`T006A` (`MSEHT`) ASYNC PHRASE INDEX RATIO 0.200000 FUZZY SEARCH INDEX ON SEARCH ONLY OFF FAST PREPROCESS ON TEXT MINING OFF TEXT ANALYSIS OFF TOKEN SEPARATORS '\/;,.:-_()[]<>!?*@+{}=`&#$~|' COMPRESSION LEVEL 0


--  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

SELECT * FROM `T006A` WHERE `MANDT`='000' AND `SPRAS`='D' AND `MSEHI`='MGQ';
SELECT * FROM `T006A` WHERE `MANDT`='000' AND `SPRAS`='D' AND (`MSEHI`='MGq' OR `MSEHI`='MGQ');

SELECT * FROM "T006A" WHERE "MANDT"='000' AND "SPRAS"='D' AND "MSEHI"='MGQ';
SELECT * FROM "T006A" WHERE "MANDT"='000' AND "SPRAS"='D' AND ("MSEHI"='MGq' OR "MSEHI"='MGQ');


INSERT INTO `T006A` (`MANDT`, `SPRAS`, `MSEHI`, `MSEH3`, `MSEH6`, `MSEHT`, `MSEHL`) VALUES ('000', 'D', 'MGQ', 'MGQ', 'mg/m3', 'mg/m3', 'Milligramm/Kubikmeter');
INSERT INTO `T006A` (`MANDT`, `SPRAS`, `MSEHI`, `MSEH3`, `MSEH6`, `MSEHT`, `MSEHL`) VALUES ('000', 'D', 'MGq', 'MGq', 'mg/tm3', 'mg/10m3', 'Milligramm/10 Kubikmeter');




