apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  serviceName: gitlab
  replicas: 1
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      hostname: 'gitlab'
      containers:
      - name: gitlab
        image: registry.gitlab.cn/omnibus/gitlab-jh:latest
        volumeMounts:
          - name: gitlab
            mountPath: /etc/gitlab
            subPath: config
          - name: gitlab
            mountPath: /var/log/gitlab
            subPath: logs
          - name: gitlab
            mountPath: /var/opt/gitlab
            subPath: data
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          value: "external_url 'https://gitlab.devops'"
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: ssh
          containerPort: 22
#        shm_size: '256m'
  volumeClaimTemplates:
    - metadata:
        name: gitlab
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi