apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  - name: ssh
    port: 22
  clusterIP: None
  selector:
    app: gitlab
